### ISSUE TITLE
One strange 41256 IC!

### ISSUE THREAD

**Issue by iosoft** [trevor-makes/avr-dram-tester#2]
I was testing all my 54 ICs (KM41256AP-12), 10 found to be dead/bad.
I tested each ICs 3 times.

But, there I ONE strange DRAM IC.
Every time, I test this IC, it gives me a random result! sometimes Green, sometimes Red.

Last night, I kept the test running for 30 mins, GREEN.
Today morning, when I turn it on, RED!
When I re-test, GREEN again!

![IMG20230329114020](https://user-images.githubusercontent.com/349968/228445040-283828dc-cbb0-4761-9583-a23056a3c47d.jpg)

**Comment by trevor-makes** [comment]
Do you have access to an oscilloscope or logic analyzer? The error pin (A1 on the Nano) does a low pulse when an error is found so you can use it to trigger a scope and look at the other lines when an error happens.

My shot in the dark guess is just the first few writes are bad, and maybe increasing the number of refresh cycles before the test could help. Try changing the `i = 8` in the code below to `i = 12` and see if it improves, and then try changing it to `i = 4` and see if it gets worse.

https://github.com/trevor-makes/avr-dram-tester/blob/20789a64593457c96db2668e6577238a8f738dc4/src/main.cpp#L86-L91

**Comment by iosoft** [comment]
> Do you have access to an oscilloscope or logic analyzer? The error pin (A1 on the Nano) does a low pulse when an error is found so you can use it to trigger a scope and look at the other lines when an error happens.
> 
> My shot in the dark guess is just the first few writes are bad, and maybe increasing the number of refresh cycles before the test could help. Try changing the `i = 8` in the code below to `i = 12` and see if it improves, and then try changing it to `i = 4` and see if it gets worse.
> 
> https://github.com/trevor-makes/avr-dram-tester/blob/20789a64593457c96db2668e6577238a8f738dc4/src/main.cpp#L86-L91

I will update you soon.

**Comment by iosoft** [comment]
Sorry, I forgot to give you update....

I reuploaded your newer version of code (with original i = 8) and tested this strange IC.

GREEN always.
I also kept it running for 1 hour.... GREEN.

Thanks for your great work.

**Comment by trevor-makes** [comment]
So the strange IC was working now without any changes? Maybe it was just a fluke.

**Comment by iosoft** [comment]
Yes, tested yesterday..... no issue :)

**Comment by iosoft** [comment]
No issue today. 100% working.

P.S. Pls update the cover image to show Both 4164 and 41256 ICs.
https://raw.githubusercontent.com/trevor-makes/avr-dram-tester/main/images/circuit.png
