### ISSUE TITLE
Inconsistent results between testers

### ISSUE THREAD

**Issue by SanPollo** [trevor-makes/avr-dram-tester#5]
First of all, thank you so much for sharing this project. I made it on perfboard as I wanted a bit more of a permanent solution than the breadboard because I'm starting to do more and more repairs, and am now building new machines.

I ordered some DRAM chips from AliExpress which is, of course, always hit and miss.

The simple test shows green for all 10 chips, but the March-C test fails for each. My friend built a different tester from https://ezcontents.org/4164-dynamic-ram-arduino and each chip passed!

I know my tester works, because not only did I do a full continuity test before I powered it up the first time, but some of my other existing DRAM chips test fine.

Do you know why your method may be showing the chips bad, whereas the one on the other page shows them as good?

Thanks in advance for any advice.

**Comment by iosoft** [comment]
Pls share a pic of your setup.


I also build the tester on breadboard only.
I was testing all my 54 ICs (KM41256AP-12), 10 found to be dead/bad.
I tested each ICs 3 times.

Full story here -
https://github.com/trevor-makes/avr-dram-tester/issues/2

**Comment by SanPollo** [comment]
@iosoft sure. It's a bit of a mess! I plan to learn KiCAD soon, and will probably make a board based on this. If I do, I will rearrange the pins in the software so I can route the traces better.

![image](https://github.com/user-attachments/assets/e3c691e0-4637-4805-9a28-522f6bdbfd67)

![image](https://github.com/user-attachments/assets/7945fbdf-066a-499b-9240-e767c6167076)

**Comment by SanPollo** [comment]
@trevor-makes I just watched the [other guy's video](https://youtu.be/fX4Qqv7pAvQ) and then rewatched yours. If I understand correctly, the other version just writes 1s to each address and then reads them back, so it wouldn't catch a lot of faults that yours does. Is this correct?

**Comment by trevor-makes** [comment]
@SanPollo Hi! Yes, it does look like the other tester just writes all 1s and reads them back one row at a time. I think at the very least it should do a 2nd pass writing 0s just to make sure the data line isn't simply stuck high. It's also using digitalWrite and digitalRead which are quite slow so the timing won't resemble the memory access and refresh cycles of an 8-bit computer bus.

If you do have other DRAM chips that work with my tester, I would be confident that those chips and the tester are working, and that the new DRAM chips are likely bad. If you have access to an oscilloscope or logic analyzer, try the timing mode that I demonstrated in my video. That may be helpful in visually confirming if any bits are stuck high.

**Comment by SanPollo** [comment]
@trevor-makes many thanks for the explanation.
